import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Product",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script src="https://cdn.botpress.cloud/webchat/v0/inject.js"></script>
        <script
          src="https://mediafiles.botpress.cloud/2c8d4316-c58b-4e76-889a-085a8c3c394b/webchat/config.js"
          defer
        ></script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
